import { createTheme, rem } from '@mantine/core'

export const siteTokens = {
  accent: '#f2a93b',
  accent2: '#e94e1b',
  activeInk: '#1a0f06',
  background: '#0d0805',
  border: '#2a1d11',
  borderStrong: '#3b281a',
  dimmer: '#5b4d3a',
  foreground: '#f4ead8',
  foregroundDim: '#8b7a5e',
  foregroundMuted: '#c9b896',
  mycelium: '#38d9a9',
  purple: '#b197fc',
  raised: '#1d1610',
  rule: '#2a1d11',
  sunken: '#080503',
  surface: '#15100a',
  success: '#a3d97c',
  terminalBarEnd: '#120b07',
  terminalBarStart: '#1a120b',
  terminalBg: '#0a0604',
  terminalText: '#d8c9aa',
  windowGreen: '#28c840',
  windowGreenBorder: '#21a232',
  windowRed: '#ff5f57',
  windowRedBorder: '#cc4640',
  windowYellow: '#febc2e',
  windowYellowBorder: '#cc9627',
}

export const siteCssVariables = {
  '--accent': 'var(--glow-spore)',
  '--accent-2': 'var(--glow-cap)',
  '--bg-base': 'var(--site-bg)',
  '--bg-raised': 'var(--site-raised)',
  '--bg-sunken': 'var(--site-sunken)',
  '--bg-surface': 'var(--site-surface)',
  '--border-1': 'var(--site-border)',
  '--border-2': 'var(--site-rule)',
  '--border-3': 'var(--site-border-strong)',
  '--fg-1': 'var(--site-fg)',
  '--fg-2': 'var(--site-muted)',
  '--fg-3': 'var(--site-dim)',
  '--fg-4': 'var(--site-dimmer)',
  '--font-mono': 'var(--mantine-font-family-monospace)',
  '--glow-cap': siteTokens.accent2,
  '--glow-mycelium': siteTokens.mycelium,
  '--glow-purple': siteTokens.purple,
  '--glow-spore': siteTokens.accent,
  '--site-active-ink': siteTokens.activeInk,
  '--site-bg': siteTokens.background,
  '--site-border': siteTokens.border,
  '--site-border-strong': siteTokens.borderStrong,
  '--site-dim': siteTokens.foregroundDim,
  '--site-dimmer': siteTokens.dimmer,
  '--site-fg': siteTokens.foreground,
  '--site-muted': siteTokens.foregroundMuted,
  '--site-cap-line': 'rgba(233, 78, 27, 0.3)',
  '--site-crossword-block': '#050302',
  '--site-crossword-cell': '#1a120b',
  '--site-crossword-focus': 'rgba(242, 169, 59, 0.1)',
  '--site-hover-wash': 'rgba(255, 255, 255, 0.03)',
  '--site-notebook-bg': 'linear-gradient(180deg, #1a130b 0%, #0e0805 100%)',
  '--site-notebook-rule': 'repeating-linear-gradient(transparent, transparent 30px, rgba(242, 169, 59, 0.05) 30px, rgba(242, 169, 59, 0.05) 31px)',
  '--site-overlay-medium': 'rgba(0, 0, 0, 0.3)',
  '--site-overlay-soft': 'rgba(0, 0, 0, 0.25)',
  '--site-overlay-strong': 'rgba(0, 0, 0, 0.4)',
  '--site-overlay-subtle': 'rgba(0, 0, 0, 0.2)',
  '--site-purple-badge-bg': 'rgba(177,151,252,0.15)',
  '--site-raised': siteTokens.raised,
  '--site-rule': siteTokens.rule,
  '--site-spore-active-wash': 'rgba(242, 169, 59, 0.07)',
  '--site-spore-badge-bg': 'rgba(242,169,59,0.15)',
  '--site-spore-ring': 'rgba(242, 169, 59, 0.2)',
  '--site-spore-wash': 'rgba(242, 169, 59, 0.06)',
  '--site-sunken': siteTokens.sunken,
  '--site-surface': siteTokens.surface,
  '--site-success': siteTokens.success,
  '--site-success-wash': 'rgba(76,175,80,0.15)',
  '--site-terminal-bar-bg': `linear-gradient(to bottom, ${siteTokens.terminalBarStart}, ${siteTokens.terminalBarEnd})`,
  '--site-terminal-bg': siteTokens.terminalBg,
  '--site-terminal-shadow': '0 30px 80px -20px rgba(0, 0, 0, 0.6)',
  '--site-terminal-text': siteTokens.terminalText,
  '--site-window-green': siteTokens.windowGreen,
  '--site-window-green-border': siteTokens.windowGreenBorder,
  '--site-window-red': siteTokens.windowRed,
  '--site-window-red-border': siteTokens.windowRedBorder,
  '--site-window-yellow': siteTokens.windowYellow,
  '--site-window-yellow-border': siteTokens.windowYellowBorder,
}

// Mantine `other` tokens are for JS-side theme access (e.g. useMantineTheme().other.textPrimary)
export const themeTokens = createTheme({
  other: {
    borderLight: '#2a1d11',
    brand: {
      bark: '#a86a2c',
      cap: '#e94e1b',
      capSoft: '#c63d14',
      ink: '#0b0000',
      moss: '#4caf50',
      mossDeep: '#2e7d32',
      soil: '#3b1f0f',
      spores: '#f2a93b',
      sporesSoft: '#fabf64',
      stipe: '#fffdf8',
      stipeShade: '#f6efde',
    },
    containerPadding: rem(28),
    gradients: {
      decay: 'linear-gradient(135deg, var(--mantine-color-fruiting-6), var(--mantine-color-decay-6))',
      default: 'linear-gradient(135deg, var(--mantine-color-mycelium-6), var(--mantine-color-spore-6))',
      warm: 'linear-gradient(135deg, var(--mantine-color-brandCap-6), var(--mantine-color-brandSpore-5))',
    },
    site: {
      accent: siteTokens.accent,
      accent2: siteTokens.accent2,
      activeInk: siteTokens.activeInk,
      background: siteTokens.background,
      border: siteTokens.border,
      borderStrong: siteTokens.borderStrong,
      foreground: siteTokens.foreground,
      foregroundDim: siteTokens.foregroundDim,
      foregroundMuted: siteTokens.foregroundMuted,
      raised: siteTokens.raised,
      rule: siteTokens.rule,
      sunken: siteTokens.sunken,
      surface: siteTokens.surface,
      success: siteTokens.success,
      terminalBg: siteTokens.terminalBg,
      terminalText: siteTokens.terminalText,
    },
    textPrimary: siteTokens.foreground,
    textSecondary: siteTokens.foregroundMuted,
    toolColors: {
      annulus: 'var(--mantine-color-chitin-3)',
      canopy: 'var(--mantine-color-mycelium-3)',
      cap: 'var(--mantine-color-lichen-4)',
      cortina: 'var(--mantine-color-fruiting-5)',
      hyphae: 'var(--mantine-color-substrate-5)',
      hymenium: 'var(--mantine-color-gill-4)',
      lamella: 'var(--mantine-color-hymenium-5)',
      mycelium: 'var(--mantine-color-mycelium-5)',
      rhizome: 'var(--mantine-color-spore-4)',
      septa: 'var(--mantine-color-mycelium-7)',
      spore: 'var(--mantine-color-spore-3)',
      stipe: 'var(--mantine-color-brandStipe-6)',
      volva: 'var(--mantine-color-decay-4)',
    },
  },
})
